# -*- coding: utf-8 -*-
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "debian6"
  config.vm.network :hostonly, "192.168.10.12"
  config.vm.host_name = "debian6-2"

  config.vm.customize do |vm|
    vm.memory_size = 1024
    vm.name = "debian6-2"
  end

  config.vm.provision :shell, :inline => "echo 'if [ \"\$BASH\" ]; then  if [ -f ~/.bashrc ]; then . ~/.bashrc; fi; fi; if `tty -s`; then mesg n; fi' >/root/.profile"
  config.vm.provision :shell, :inline => 'echo "Finished provisioning normally"'
end
