print("hello. it is OK.")
print(func_addition(10, 20))
print(func_addition(10, 20))
print(func_open())
print(func_open())
print(func_open())
print(func_close())
print(func_close())
print(func_close())