MK_CFG_DIR = /usr/local/share/make_cfg
include $(MK_CFG_DIR)/make.defs

CSRC = sample.c
EXETARGET = sample

WARN +=
OPPFLAGS +=
DEPOBJS =
LDFLAGS =
LDLIBS = -lpthread

include $(MK_CFG_DIR)/make.rules
