MK_CFG_DIR = /usr/local/share/make_cfg
include $(MK_CFG_DIR)/make.defs

CSRC = tcutil.c
EXETARGET = tcutil

WARN +=
OPPFLAGS +=
DEPOBJS =
LDFLAGS =
LDLIBS = -ltokyocabinet

include $(MK_CFG_DIR)/make.rules