# -*- mode: ruby -*-
# vi: set ft=ruby :

# http://www.vagrantbox.es/
# vagrant box add ubuntu-12.04-x64 http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box

Vagrant::Config.run do |config|
  config.vm.box = "ubuntu-12.04-x64"
  config.vm.network :hostonly, "192.168.12.30"
  config.vm.host_name = "ubuntu-12-01-1"

  config.vm.customize do |vm|
    vm.memory_size = 1024
    vm.name = "debian6-1"
  end

  config.vm.provision :shell, :inline => "echo 'if [ \"\$BASH\" ]; then  if [ -f ~/.bashrc ]; then . ~/.bashrc; fi; fi; if `tty -s`; then mesg n; fi' >/root/.profile"
  config.vm.provision :shell, :inline => 'echo "Finished provisioning normally"'
end
