#SUBDIR = foo bar
#.PHONY: all $(SUBDIR)
.PHONY: all foo bar

#all: $(SUBDIR)
#all:
#	echo "ok"
#$(SUBDIR):
foo bar:
	echo $@
#	make --directory=$@

#foo := foo bar
#foo = foo bar
#.PHONY: $(foo)
#all: $(foo)
#$(foo):
#	make --directory=$@


#$(foo):
#	echo $@
#	make -C $@
#	make --directory=$@

