MK_CFG_DIR = /usr/local/share/make_cfg
include $(MK_CFG_DIR)/make.defs

CSRC      = snprintf.c
EXETARGET = snprintf

WARN     +=
OPPFLAGS +=
DEPOBJS   =
LDFLAGS   =
LDLIBS    = 

include $(MK_CFG_DIR)/make.rules