MKCFG_DIR = ../../../../gnu_make/nmake_cfg
include $(MKCFG_DIR)/make.defs

EXETARGET = sptree_dumper
CSRC = 
CXXSRC = sptree_dumper.cc

OPPFLAGS += -I../../lib
LDFLAGS = -L/home/z/lib
LDLIBS = -lsptree

include $(MKCFG_DIR)/make.rules
