MKCFG_DIR = ../../../../gnu_make/nmake_cfg
include $(MKCFG_DIR)/make.defs

EXETARGET = sptree_dump_header
CSRC = 
CXXSRC = sptree_dump_header.cc

OPPFLAGS += -I../../lib
LDFLAGS = -L/home/z/lib
LDLIBS = -lsptree

include $(MKCFG_DIR)/make.rules
