MK_CFG_DIR = $(HOME)/git/sample-codes/gnu_make/nmake_cfg
include $(MK_CFG_DIR)/make.defs

CSRC = test.c
EXETARGET = test

WARN +=
OPPFLAGS +=
DEPOBJS =
LDFLAGS =
LDLIBS = 

include $(MK_CFG_DIR)/make.rules
