MK_CFG_DIR = ../../gnu_make/nmake_cfg/
include $(MK_CFG_DIR)/make.defs

EXETARGET = dumper
CSRC = 
CXXSRC = dumper.cc

WARN +=
OPPFLAGS += -I./include
LDFLAGS = 
LDLIBS = 

include $(MK_CFG_DIR)/make.rules.formac
