MK_CFG_DIR = /usr/local/share/make_cfg
include $(MK_CFG_DIR)/make.defs

#LIBNAME = nshm
#LIBVERSION=1
CSRC = sample.c
EXETARGET = sample

WARN +=
OPPFLAGS +=
DEPOBJS =
LDFLAGS =
LDLIBS = -lpthread -lnshm

include $(MK_CFG_DIR)/make.rules
