MKCFG_DIR = ../../../gnu_make/nmake_cfg
include $(MKCFG_DIR)/make.defs

EXETARGET = simpled
CSRC = simpled.c
CXXSRC = 

OPPFLAGS += -I../../lib
LDFLAGS = -lpthread
LDLIBS =

include $(MKCFG_DIR)/make.rules
